var table = window.prompt("Table Of: " , "5");
document.write("Table of " + table);
document.write("<br>");
document.write("<br>"+table + " X 1 = " + 1*table);
document.write("<br>"+table + " X 2 =" + 2*table);
document.write("<br>"+table + " X 3 =" + 3*table);
document.write("<br>"+table + " X 4 =" + 4*table);
document.write("<br>"+table + " X 5 =" + 5*table);
document.write("<br>"+table + " X 6 =" + 6*table);
document.write("<br>"+table + " X 7 =" + 7*table);
document.write("<br>"+table + " X 8 =" + 8*table);
document.write("<br>"+table + " X 9 =" + 9*table);
document.write("<br>"+table + " X 10 =" + 10 *table);